name: CI + Haru Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-and-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install ruff pytest openai pygit2

      # .github/workflows/ci.yml
      - name: Lint & Test
        run: |
          ruff check . || true
          pytest -q || true

      - name: Generate Haru Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          python scripts/haru_review.py > review.md

      - name: Comment Review on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: review.md

