name: CI + Haru Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install ruff pytest openai pygit2

      # .github/workflows/ci.yml
      - name: Lint & Test
        run: |
<<<<<<< HEAD
          echo "== debug =="
          pwd
          ls -la
          git ls-files | grep -E '^\.ruff\.toml$' || true
          git ls-files | grep -E '^get-pip\.py$' || echo "get-pip.py not tracked (OK)"
          echo "ruff version: $(ruff --version)"
          echo "== run ruff =="
          ruff check . --config ./.ruff.toml --exclude get-pip.py --exclude papers --exclude checkpoints || true
          echo "== run pytest =="
=======
          ruff check . --config ./.ruff.toml --exclude get-pip.py --exclude papers --exclude checkpoints || true
>>>>>>> e547c00 (ci: minimal valid workflow for PRs)
          pytest -q || true

      - name: Generate Haru Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          python scripts/haru_review.py > review.md

      - name: Comment Review on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: review.md